apiVersion: apps/v1
kind: Deployment
metadata:
  name: desafio5
spec:
  replicas: 2
  selector:
    matchLabels:
      app: desafio3
  template:
    metadata:
      labels:
        app: desafio3
    spec:
      containers:
        - name: exciting_lumiere
          image: desafio4:latest
          ports:
            - containerPort: 80
