apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubernetes
  template:
    metadata:
      labels:
        app: kubernetes
    spec:
      containers:
        - name: desafio4
          image: desafio4:1.0
          ports:
            - containerPort: 80
